#
# Makefile for the Micrel network device drivers.
#

obj-$(CONFIG_ARM_KS8695_ETHER) += ks8695net.o
obj-$(CONFIG_KS8842) += ks8842.o
obj-$(CONFIG_KS8851) += ks8851.o
obj-$(CONFIG_KS8851_MLL) += ks8851_mll.o
obj-$(CONFIG_KSZ884X_PCI) += ksz884x.o
obj-$(CONFIG_SPI_KSZ8463) += spi-ksz8463.o
obj-$(CONFIG_I2C_KSZ8863) += i2c-ksz8863.o
obj-$(CONFIG_SPI_KSZ8863) += spi-ksz8863.o
obj-$(CONFIG_SPI_KSZ8795) += spi-ksz8795.o
obj-$(CONFIG_SPI_KSZ8895) += spi-ksz8895.o
obj-$(CONFIG_I2C_KSZ9897) += i2c-ksz9897.o
obj-$(CONFIG_SPI_KSZ9897) += spi-ksz9897.o
obj-$(CONFIG_NET_CENTAUR) += ksz8695.o
obj-$(CONFIG_NET_PEGASUS) += ksz8692.o
obj-$(CONFIG_KSZ8462_HLI) += ksz8462_h.o
