#!/bin/sh
#
# Create a bridge linking two devices.
#


create_br_dev() {
    ETH=0

    if [ ! -z "$1" ]; then
        ETH=$1
    fi

    ETHDEV=eth
    PORTS=2
    START=$ETH

    VLAN=0
    if [ -e "/sys/class/net/eth$ETH/sw/two_dev" ]; then
        VLAN=$(cat /sys/class/net/eth$ETH/sw/two_dev)
        if [ $VLAN -eq 2 ]; then
            ifconfig eth1 0.0.0.0
            VLAN=0
        fi
    fi
    if [ -e "/sys/class/net/lan1" ]; then
        ETHDEV=lan
        START=1
        p=2
        while [ -e "sys/class/net/lan$p" ]; do
            let p=$p+1
        done
        PORTS=$p
        VLAN=2
    fi
    [ $VLAN -eq 0 ] && exit 0

    IP=$(ifconfig eth$ETH | grep "inet addr" | cut -d":" -f2 | cut -d" " -f1)
    SUBNET1=$(echo "$IP" | cut -d"." -f1)
    SUBNET2=$(echo "$IP" | cut -d"." -f2)
    SUBNET3=$(echo "$IP" | cut -d"." -f3)
    SUBNET4=$(echo "$IP" | cut -d"." -f4)

    MAC=$(ifconfig eth$ETH | grep "HWaddr " | cut -d" " -f11)
    MAC_1=$(echo $MAC | cut -d":" -f1)
    MAC_2=$(echo $MAC | cut -d":" -f2)
    MAC_3=$(echo $MAC | cut -d":" -f3)
    MAC_4=$(echo $MAC | cut -d":" -f4)
    MAC_5=$(echo $MAC | cut -d":" -f5)
    MAC_6=$(echo $MAC | cut -d":" -f6)

    p=$START
    while [ $p -lt $PORTS ]; do
        ifconfig $ETHDEV$p hw ether $MAC
        ifconfig $ETHDEV$p 0.0.0.0
        let p=$p+1
    done

    brctl addbr br0
    if [ $VLAN -eq 2 ]; then
        ifconfig eth$ETH 0.0.0.0
        if [ -e /sys/class/net/br0/bridge/vlan_filtering ]; then
            echo "write 1 to vlan_filtering to enable VLAN filtering"
        fi
    fi

    p=$START
    while [ $p -lt $PORTS ]; do
        brctl addif br0 $ETHDEV$p
        let p=$p+1
    done

    ifconfig br0 $SUBNET1.$SUBNET2.$SUBNET3.$SUBNET4
}

start() {
    create_br_dev
}

case "$1" in
    start)
        start
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
