/* SPDX-License-Identifier: GPL-2.0
 *
 * Microchip KSZ8463 register definitions
 *
 * Copyright (c) 2019 Microchip Technology Inc.
 *	Tristram Ha <Tristram.Ha@microchip.com>
 */

#ifndef __KSZ8463_REG_H
#define __KSZ8463_REG_H

#define KS_PORT_M			0x7

#define KS_PRIO_M			0x3
#define KS_PRIO_S			2

#define REG_CHIP_ID0			0x00

#define FAMILY_ID			0x84

#define REG_CHIP_ID1			0x01

#define SW_CHIP_ID_M			0xF0
#define SW_CHIP_ID_S			4
#define SW_REVISION_M			0x0E
#define SW_REVISION_S			1
#define SW_START			BIT(0)

#define CHIP_ID_63			0x40
#define CHIP_ID_63_R			0x50

#define REG_SW_CTRL_1			0x02

#define SW_PASS_ALL			BIT(15)
#define SW_TX_FLOW_CTRL			BIT(13)
#define SW_RX_FLOW_CTRL			BIT(12)
#define SW_CHECK_LENGTH			BIT(11)
#define SW_AGING_ENABLE			BIT(10)
#define SW_FAST_AGING			BIT(9)
#define SW_AGGR_BACKOFF			BIT(8)
#define SW_IN_RATE_LIMIT_FLOW_CTRL	BIT(5)
#define SW_PASS_PAUSE			BIT(3)
#define SW_LINK_AUTO_AGING		BIT(0)

#define REG_SW_CTRL_2			0x04

#define SW_VLAN_ENABLE			BIT(15)
#define SW_IGMP_SNOOP			BIT(14)
#define SW_IPV6_MLD_SNOOP		BIT(13)
#define SW_IPV6_MLD_OPTION		BIT(12)
#define SW_MIRROR_RX_TX			BIT(8)
#define UNICAST_VLAN_BOUNDARY		BIT(7)
#define MULTICAST_STORM_DISABLE		BIT(6)
#define SW_BACK_PRESSURE		BIT(5)
#define FAIR_FLOW_CTRL			BIT(4)
#define NO_EXC_COLLISION_DROP		BIT(3)
#define SW_HUGE_PACKET			BIT(2)
#define SW_LEGAL_PACKET			BIT(1)
#define SW_BUF_RESERVE			BIT(0)

#define REG_SW_CTRL_3			0x06

#define BROADCAST_STORM_RATE_LO		0xFF00
#define SW_HALF_DUPLEX			BIT(6)
#define SW_FLOW_CTRL			BIT(5)
#define SW_10_MBIT			BIT(4)
#define SW_REPLACE_VID			BIT(3)
#define BROADCAST_STORM_RATE_HI		0x0007
#define BROADCAST_STORM_RATE		0x07FF

#define REG_SW_CTRL_6			0x0C

#define SW_802_1P_MAP_M			KS_PRIO_M
#define SW_802_1P_MAP_S			KS_PRIO_S

#define REG_SW_CTRL_7			0x0E

#define SW_UNKNOWN_DA_ENABLE		BIT(7)
#define SW_UNKNOWN_DA_2_PORT3		BIT(2)
#define SW_UNKNOWN_DA_2_PORT2		BIT(1)
#define SW_UNKNOWN_DA_2_PORT1		BIT(0)

#define REG_SW_MAC_ADDR_0		0x10
#define REG_SW_MAC_ADDR_1		0x11
#define REG_SW_MAC_ADDR_2		0x12
#define REG_SW_MAC_ADDR_3		0x13
#define REG_SW_MAC_ADDR_4		0x14
#define REG_SW_MAC_ADDR_5		0x15

#define REG_TOS_PRIO_CTRL_1		0x16
#define REG_TOS_PRIO_CTRL_2		0x18
#define REG_TOS_PRIO_CTRL_3		0x1A
#define REG_TOS_PRIO_CTRL_4		0x1C
#define REG_TOS_PRIO_CTRL_5		0x1E
#define REG_TOS_PRIO_CTRL_6		0x20
#define REG_TOS_PRIO_CTRL_7		0x22
#define REG_TOS_PRIO_CTRL_8		0x24

#define REG_IND_DATA_1			0x26

#define TABLE_READ_NOT_COMPLETE		BIT(7)

#define REG_IND_DATA_2			0x28
#define REG_IND_DATA_3			0x2A
#define REG_IND_DATA_4			0x2C
#define REG_IND_DATA_5			0x2E

#define REG_IND_CTRL_0			0x30

#define TABLE_READ			BIT(12)
#define TABLE_SELECT_S			10
#define TABLE_STATIC_MAC_V		0
#define TABLE_VLAN_V			1
#define TABLE_DYNAMIC_MAC_V		2
#define TABLE_MIB_V			3
#define TABLE_STATIC_MAC		(TABLE_STATIC_MAC_V << TABLE_SELECT_S)
#define TABLE_VLAN			(TABLE_VLAN_V << TABLE_SELECT_S)
#define TABLE_DYNAMIC_MAC		(TABLE_DYNAMIC_MAC_V << TABLE_SELECT_S)
#define TABLE_MIB			(TABLE_MIB_V << TABLE_SELECT_S)
#define TABLE_ENTRY_MASK		0x03FF

#define REG_IND_DATA_CHECK		REG_IND_DATA_1
#define REG_IND_DATA_HI			REG_IND_DATA_2
#define REG_IND_DATA_LO			REG_IND_DATA_4

#define PHY1_REG_CTRL			0x4C
#define PHY1_REG_STATUS			0x4E
#define PHY1_REG_ID_1			0x50
#define PHY1_REG_ID_2			0x52
#define PHY1_REG_AUTO_NEGOTIATION	0x54
#define PHY1_REG_REMOTE_CAPABILITY	0x56
#define PHY2_REG_CTRL			0x58
#define PHY2_REG_STATUS			0x5A
#define PHY2_REG_ID_1			0x5C
#define PHY2_REG_ID_2			0x5E
#define PHY2_REG_AUTO_NEGOTIATION	0x60
#define PHY2_REG_REMOTE_CAPABILITY	0x62
#define PHY1_REG_LINK_MD		0x64
#define PHY1_REG_PHY_CTRL		0x66
#define PHY2_REG_LINK_MD		0x68
#define PHY2_REG_PHY_CTRL		0x6A

#define PHY_REG_CTRL			0

#define PHY_RESET_NOT			BIT(15)
#define PHY_LOOPBACK			BIT(14)
#define PHY_SPEED_100MBIT		BIT(13)
#define PHY_AUTO_NEG_ENABLE		BIT(12)
#define PHY_POWER_DOWN			BIT(11)
#define PHY_MII_DISABLE_NOT		BIT(10)
#define PHY_AUTO_NEG_RESTART		BIT(9)
#define PHY_FULL_DUPLEX			BIT(8)
#define PHY_COLLISION_TEST_NOT		BIT(7)
#define PHY_HP_MDIX			BIT(5)
#define PHY_FORCE_MDIX			BIT(4)
#define PHY_AUTO_MDIX_DISABLE		BIT(3)
#define PHY_REMOTE_FAULT_DISABLE	BIT(2)
#define PHY_TRANSMIT_DISABLE		BIT(1)
#define PHY_LED_DISABLE			BIT(0)

#define PHY_REG_STATUS			1

#define PHY_100BT4_CAPABLE		BIT(15)
#define PHY_100BTX_FD_CAPABLE		BIT(14)
#define PHY_100BTX_CAPABLE		BIT(13)
#define PHY_10BT_FD_CAPABLE		BIT(12)
#define PHY_10BT_CAPABLE		BIT(11)
#define PHY_MII_SUPPRESS_CAPABLE_NOT	BIT(6)
#define PHY_AUTO_NEG_ACKNOWLEDGE	BIT(5)
#define PHY_REMOTE_FAULT		BIT(4)
#define PHY_AUTO_NEG_CAPABLE		BIT(3)
#define PHY_LINK_STATUS			BIT(2)
#define PHY_JABBER_DETECT		BIT(1)
#define PHY_EXTENDED_CAPABILITY		BIT(0)

#define PHY_REG_ID_1			2
#define PHY_REG_ID_2			3

/* PHY id is reserved. */
#define KSZ8463_ID_HI			0x0022
#define KSZ8463_ID_LO			0x1430

#define PHY_REG_AUTO_NEGOTIATION	4

#define PHY_AUTO_NEG_NEXT_PAGE_NOT	BIT(15)
#define PHY_AUTO_NEG_REMOTE_FAULT_NOT	BIT(13)
#define PHY_AUTO_NEG_SYM_PAUSE		BIT(10)
#define PHY_AUTO_NEG_100BT4		BIT(9)
#define PHY_AUTO_NEG_100BTX_FD		BIT(8)
#define PHY_AUTO_NEG_100BTX		BIT(7)
#define PHY_AUTO_NEG_10BT_FD		BIT(6)
#define PHY_AUTO_NEG_10BT		BIT(5)
#define PHY_AUTO_NEG_SELECTOR		0x001F
#define PHY_AUTO_NEG_802_3		0x0001

#define PHY_REG_REMOTE_CAPABILITY	5

#define PHY_REMOTE_NEXT_PAGE_NOT	BIT(15)
#define PHY_REMOTE_ACKNOWLEDGE_NOT	BIT(14)
#define PHY_REMOTE_REMOTE_FAULT_NOT	BIT(13)
#define PHY_REMOTE_SYM_PAUSE		BIT(10)
#define PHY_REMOTE_100BTX_FD		BIT(8)
#define PHY_REMOTE_100BTX		BIT(7)
#define PHY_REMOTE_10BT_FD		BIT(6)
#define PHY_REMOTE_10BT			BIT(5)

#define PHY_REG_LINK_MD			29

#define PHY_START_CABLE_DIAG		BIT(15)
#define PHY_CABLE_DIAG_RESULT		0x6000
#define PHY_CABLE_STAT_NORMAL		0x0000
#define PHY_CABLE_STAT_OPEN		0x2000
#define PHY_CABLE_STAT_SHORT		0x4000
#define PHY_CABLE_STAT_FAILED		0x6000
#define PHY_CABLE_10M_SHORT		BIT(12)
#define PHY_CABLE_FAULT_COUNTER		0x01FF

#define PHY_REG_PHY_CTRL		30

#define PHY_STAT_REVERSED_POLARITY	BIT(5)
#define PHY_STAT_MDIX			BIT(4)
#define PHY_FORCE_LINK			BIT(3)
#define PHY_POWER_SAVING_DISABLE	BIT(2)
#define PHY_REMOTE_LOOPBACK		BIT(1)

#define REG_PORT_1_CTRL_1		0x6C
#define REG_PORT_2_CTRL_1		0x84
#define REG_PORT_3_CTRL_1		0x9C

#define PORT_SA_MAC2			BIT(11)
#define PORT_SA_MAC1			BIT(10)
#define PORT_DROP_TAG			BIT(9)
#define PORT_2_QUEUES_ENABLE		BIT(8)
#define PORT_BROADCAST_STORM		BIT(7)
#define PORT_DIFFSERV_ENABLE		BIT(6)
#define PORT_802_1P_ENABLE		BIT(5)
#define PORT_BASED_PRIORITY_MASK	0x18
#define PORT_BASED_PRIORITY_BASE	0x03
#define PORT_BASED_PRIO_S		3
#define PORT_PORT_PRIO_0		0x00
#define PORT_PORT_PRIO_1		0x08
#define PORT_PORT_PRIO_2		0x10
#define PORT_PORT_PRIO_3		0x18
#define PORT_INSERT_TAG			BIT(2)
#define PORT_REMOVE_TAG			BIT(1)
#define PORT_4_QUEUES_ENABLE		BIT(0)

#define REG_PORT_1_CTRL_2		0x6E
#define REG_PORT_2_CTRL_2		0x86
#define REG_PORT_3_CTRL_2		0x9E

#define PORT_INGRESS_FILTER		BIT(14)
#define PORT_DISCARD_NON_VID		BIT(13)
#define PORT_FORCE_FLOW_CTRL		BIT(12)
#define PORT_BACK_PRESSURE		BIT(11)
#define PORT_TX_ENABLE			BIT(10)
#define PORT_RX_ENABLE			BIT(9)
#define PORT_LEARN_DISABLE		BIT(8)
#define PORT_MIRROR_SNIFFER		BIT(7)
#define PORT_MIRROR_RX			BIT(6)
#define PORT_MIRROR_TX			BIT(5)
#define PORT_802_1P_REMAPPING		BIT(3)
#define PORT_VLAN_MEMBERSHIP		KS_PORT_M

#define REG_PORT_1_CTRL_VID		0x70
#define REG_PORT_2_CTRL_VID		0x88
#define REG_PORT_3_CTRL_VID		0xA0

#define PORT_DEFAULT_VID		0x0001

#define REG_PORT_1_CTRL_3		0x72
#define REG_PORT_2_CTRL_3		0x8A
#define REG_PORT_3_CTRL_3		0xA2

#define PORT_3_MII_MAC_MODE		BIT(7)

#define PORT_INGRESS_LIMIT_MODE		0x0C
#define PORT_INGRESS_ALL		0x00
#define PORT_INGRESS_UNICAST		0x04
#define PORT_INGRESS_MULTICAST		0x08
#define PORT_INGRESS_BROADCAST		0x0C
#define PORT_COUNT_IFG			BIT(1)
#define PORT_COUNT_PREAMBLE		BIT(0)

#define REG_PORT_1_IN_RATE_0		0x74
#define REG_PORT_2_IN_RATE_0		0x8C
#define REG_PORT_3_IN_RATE_0		0xA4

#define PORT_3_INVERTED_REFCLK		BIT(7)

#define REG_PORT_1_IN_RATE_1		0x76
#define REG_PORT_2_IN_RATE_1		0x8E
#define REG_PORT_3_IN_RATE_1		0xA6

#define PORT_PRIO_RATE			0x0F
#define PORT_PRIO_RATE_S		4

#define REG_PORT_1_OUT_RATE_0		0x78
#define REG_PORT_2_OUT_RATE_0		0x90
#define REG_PORT_3_OUT_RATE_0		0xA8

#define PORT_OUT_LIMIT_FLOW_CTRL	BIT(7)

#define REG_PORT_1_OUT_RATE_1		0x7A
#define REG_PORT_2_OUT_RATE_1		0x92
#define REG_PORT_3_OUT_RATE_1		0xAA

#define REG_PORT_1_LINK_MD_CTRL		0x7C
#define REG_PORT_2_LINK_MD_CTRL		0x94

#define PORT_CABLE_10M_SHORT		BIT(15)
#define PORT_CABLE_DIAG_RESULT		0x6000
#define PORT_CABLE_STAT_NORMAL		0x0000
#define PORT_CABLE_STAT_OPEN		0x2000
#define PORT_CABLE_STAT_SHORT		0x4000
#define PORT_CABLE_STAT_FAILED		0x6000
#define PORT_START_CABLE_DIAG		BIT(12)
#define PORT_FORCE_LINK			BIT(11)
#define PORT_PHY_REMOTE_LOOPBACK	BIT(9)
#define PORT_CABLE_FAULT_COUNTER	0x1FF

#define REG_PORT_1_CTRL_4		0x7E
#define REG_PORT_2_CTRL_4		0x96

#define PORT_TX_DISABLE			BIT(14)
#define PORT_AUTO_NEG_RESTART		BIT(13)
#define PORT_REMOTE_FAULT_DISABLE	BIT(12)
#define PORT_POWER_DOWN			BIT(11)
#define PORT_AUTO_MDIX_DISABLE		BIT(10)
#define PORT_FORCE_MDIX			BIT(9
#define PORT_LOOPBACK			BIT(8)
#define PORT_AUTO_NEG_ENABLE		BIT(7)
#define PORT_FORCE_100_MBIT		BIT(6)
#define PORT_FORCE_FULL_DUPLEX		BIT(5)
#define PORT_AUTO_NEG_SYM_PAUSE		BIT(4)
#define PORT_AUTO_NEG_100BTX_FD		BIT(3)
#define PORT_AUTO_NEG_100BTX		BIT(2)
#define PORT_AUTO_NEG_10BT_FD		BIT(1)
#define PORT_AUTO_NEG_10BT		BIT(0)

#define REG_PORT_1_STATUS		0x80
#define REG_PORT_2_STATUS		0x98

#define PORT_HP_MDIX			BIT(15)
#define PORT_REVERSED_POLARITY		BIT(13)
#define PORT_TX_FLOW_CTRL		BIT(12)
#define PORT_RX_FLOW_CTRL		BIT(11)
#define PORT_STAT_SPEED_100MBIT		BIT(10)
#define PORT_STAT_FULL_DUPLEX		BIT(9)
#define PORT_REMOTE_FAULT		BIT(8)
#define PORT_MDIX_STATUS		BIT(7)
#define PORT_AUTO_NEG_COMPLETE		BIT(6)
#define PORT_STAT_LINK_GOOD		BIT(5)
#define PORT_REMOTE_SYM_PAUSE		BIT(4)
#define PORT_REMOTE_100BTX_FD		BIT(3)
#define PORT_REMOTE_100BTX		BIT(2)
#define PORT_REMOTE_10BT_FD		BIT(1)
#define PORT_REMOTE_10BT		BIT(0)

#define REG_PORT_CTRL_1			0x00
#define REG_PORT_CTRL_2			0x02
#define REG_PORT_CTRL_VID		0x04
#define REG_PORT_CTRL_3			0x06
#define REG_PORT_IN_RATE_0		0x08
#define REG_PORT_IN_RATE_1		0x0A
#define REG_PORT_OUT_RATE_0		0x0C
#define REG_PORT_OUT_RATE_1		0x0E
#define REG_PORT_LINK_MD_CTRL		0x10
#define REG_PORT_LINK_MD_RESULT		0x0B
#define REG_PORT_CTRL_4			0x12
#define REG_PORT_STATUS			0x14

#define PORT_CTRL_ADDR(port, addr)		\
	(addr = REG_PORT_1_CTRL_1 + (port) *	\
		(REG_PORT_2_CTRL_1 - REG_PORT_1_CTRL_1))

#define REG_SW_CTRL_8			0xAC

#define SW_PRIO_MAP_M			0x3
#define SW_PRIO_MAP_S			14
#define SW_PRIO_3_HI			(0 << SW_PRIO_MAP_S)
#define SW_PRIO_0_LO			(1 << SW_PRIO_MAP_S)
#define SW_PRIO_SPLIT			(2 << SW_PRIO_MAP_S)
#define SW_FLUSH_DYN_MAC_TABLE		BIT(10)
#define SW_FLUSH_STA_MAC_TABLE		BIT(9)
#define SW_TAIL_TAG_ENABLE		BIT(8)

#define REG_SW_CTRL_9			0xAE
#define REG_INSERT_SRC_PVID		0xAE

#define SW_UNKNOWN_VID_2_PORT3		BIT(10)
#define SW_UNKNOWN_VID_2_PORT2		BIT(9)
#define SW_UNKNOWN_VID_2_PORT1		BIT(8)
#define SW_INS_TAG_3_PORT_2		BIT(5)
#define SW_INS_TAG_3_PORT_1		BIT(4)
#define SW_INS_TAG_2_PORT_3		BIT(3)
#define SW_INS_TAG_2_PORT_1		BIT(2)
#define SW_INS_TAG_1_PORT_3		BIT(1)
#define SW_INS_TAG_1_PORT_2		BIT(0)

#define TOS_PRIO_M			KS_PRIO_M
#define TOS_PRIO_S			KS_PRIO_S

#define REG_PORT_1_MAC_ADDR_0		0xB4
#define REG_PORT_1_MAC_ADDR_1		0xB5
#define REG_PORT_1_MAC_ADDR_2		0xB2
#define REG_PORT_1_MAC_ADDR_3		0xB3
#define REG_PORT_1_MAC_ADDR_4		0xB0
#define REG_PORT_1_MAC_ADDR_5		0xB1
#define REG_PORT_2_MAC_ADDR_0		0xBA
#define REG_PORT_2_MAC_ADDR_1		0xBB
#define REG_PORT_2_MAC_ADDR_2		0xB8
#define REG_PORT_2_MAC_ADDR_3		0xB9
#define REG_PORT_2_MAC_ADDR_4		0xB6
#define REG_PORT_2_MAC_ADDR_5		0xB7

#define REG_PORT_1_RATE_CTRL_1		0xC8

#define TXQ2_RATE_CTRL_ENABLE		BIT(15)
#define TXQ1_RATE_CTRL_ENABLE		BIT(7)

#define REG_PORT_1_RATE_CTRL_2		0xCA

#define TXQ4_RATE_CTRL_ENABLE		BIT(15)
#define TXQ3_RATE_CTRL_ENABLE		BIT(7)

#define REG_PORT_2_RATE_CTRL_1		0xCE
#define REG_PORT_2_RATE_CTRL_2		0xD0
#define REG_PORT_3_RATE_CTRL_1		0xD2
#define REG_PORT_3_RATE_CTRL_2		0xD4

#define RATE_CTRL_ENABLE		BIT(7)
#define RATE_RATIO_M			0x7F

#define REG_CFG_CTRL			0xD8
#define PORT_2_COPPER			BIT(7)
#define PORT_1_COPPER			BIT(6)
#define PORT_COPPER_MODE_S		6

#define REG_PCS_EEE_CTRL		0xF3
#define PORT_2_NEXT_PAGE_ENABLE		BIT(1)
#define PORT_1_NEXT_PAGE_ENABLE		BIT(0)

#define REG_SW_RESET			0x126

#define PTP_SOFTWARE_SET		BIT(2)
#define GLOBAL_SOFTWARE_RESET		BIT(0)

#define REG_INT_ENABLE			0x190

#define REG_INT_STATUS			0x192

#define INT_PORT_1_2_LINK_CHANGE	BIT(15)

#define REG_DSP_CTRL_1			0x734
#define COPPER_RECEIVE_ADJUSTMENT	BIT(13)

/* Chip resource */

#define PRIO_QUEUES			4

#define KS_PRIO_IN_REG			4

#define TOTAL_PORT_NUM			3

/* Host port can only be last of them. */
#define SWITCH_PORT_NUM			(TOTAL_PORT_NUM - 1)

#define KSZ8463_COUNTER_NUM		0x20
#define TOTAL_KSZ8463_COUNTER_NUM	(KSZ8463_COUNTER_NUM + 2)

#define SWITCH_COUNTER_NUM		KSZ8463_COUNTER_NUM
#define TOTAL_SWITCH_COUNTER_NUM	TOTAL_KSZ8463_COUNTER_NUM

/* Common names used by other drivers */

#define P_BCAST_STORM_CTRL		REG_PORT_CTRL_1
#define P_PRIO_CTRL			REG_PORT_CTRL_1
#define P_TAG_CTRL			REG_PORT_CTRL_1
#define P_MIRROR_CTRL			REG_PORT_CTRL_2
#define P_STP_CTRL			REG_PORT_CTRL_2
#define P_PHY_CTRL			REG_PORT_CTRL_4
#define P_FORCE_CTRL			REG_PORT_CTRL_4
#define P_NEG_RESTART_CTRL		REG_PORT_CTRL_4
#define P_LINK_STATUS			REG_PORT_STATUS
#define P_SPEED_STATUS			REG_PORT_STATUS
#define P_RATE_LIMIT_CTRL		REG_PORT_CTRL_3
#define P_SA_MAC_CTRL			REG_PORT_CTRL_1
#define P_4_QUEUE_CTRL			REG_PORT_CTRL_1
#define P_2_QUEUE_CTRL			REG_PORT_CTRL_1

#define S_LINK_AGING_CTRL		REG_SW_CTRL_1
#define S_MIRROR_CTRL			REG_SW_CTRL_2
#define S_REPLACE_VID_CTRL		REG_SW_CTRL_3
#define S_802_1P_PRIO_CTRL		REG_SW_CTRL_6
#define S_UNKNOWN_DA_CTRL		REG_SW_CTRL_7
#define S_TOS_PRIO_CTRL			REG_TOS_PRIO_CTRL_1
#define S_FLUSH_TABLE_CTRL		REG_SW_CTRL_8
#define S_TAIL_TAG_CTRL			REG_SW_CTRL_8
#define S_FORWARD_INVALID_VID_CTRL	REG_SW_CTRL_9
#define S_INS_SRC_PVID_CTRL		REG_SW_CTRL_9

#define IND_ACC_TABLE(table)		((table))

/* Driver set switch broadcast storm protection at 10% rate. */
#define BROADCAST_STORM_PROT_RATE	10

/* 148,800 frames * 67 ms / 100 */
#define BROADCAST_STORM_VALUE		9969

/**
 * STATIC_MAC_TABLE_ADDR		00-0000FFFF-FFFFFFFF
 * STATIC_MAC_TABLE_FWD_PORTS		00-00070000-00000000
 * STATIC_MAC_TABLE_VALID		00-00080000-00000000
 * STATIC_MAC_TABLE_OVERRIDE		00-00100000-00000000
 * STATIC_MAC_TABLE_USE_FID		00-00200000-00000000
 * STATIC_MAC_TABLE_FID			00-03C00000-00000000
 */

#define STATIC_MAC_TABLE_ADDR		0x0000FFFF
#define STATIC_MAC_TABLE_FWD_PORTS	0x00070000
#define STATIC_MAC_TABLE_VALID		0x00080000
#define STATIC_MAC_TABLE_OVERRIDE	0x00100000
#define STATIC_MAC_TABLE_USE_FID	0x00200000
#define STATIC_MAC_TABLE_FID		0x03C00000

#define STATIC_MAC_FWD_PORTS_S		16
#define STATIC_MAC_FID_S		22

/**
 * VLAN_TABLE_VID			00-00000000-00000FFF
 * VLAN_TABLE_FID			00-00000000-0000F000
 * VLAN_TABLE_MEMBERSHIP		00-00000000-00070000
 * VLAN_TABLE_VALID			00-00000000-00080000
 */

#define VLAN_TABLE_VID			0x00000FFF
#define VLAN_TABLE_FID			0x0000F000
#define VLAN_TABLE_MEMBERSHIP		0x00070000
#define VLAN_TABLE_VALID		0x00080000

#define VLAN_TABLE_FID_S		12
#define VLAN_TABLE_MEMBERSHIP_S		16

/**
 * DYNAMIC_MAC_TABLE_ADDR		00-0000FFFF-FFFFFFFF
 * DYNAMIC_MAC_TABLE_FID		00-000F0000-00000000
 * DYNAMIC_MAC_TABLE_SRC_PORT		00-00300000-00000000
 * DYNAMIC_MAC_TABLE_TIMESTAMP		00-00C00000-00000000
 * DYNAMIC_MAC_TABLE_ENTRIES		03-FF000000-00000000
 * DYNAMIC_MAC_TABLE_MAC_EMPTY		04-00000000-00000000
 * DYNAMIC_MAC_TABLE_RESERVED		78-00000000-00000000
 * DYNAMIC_MAC_TABLE_NOT_READY		80-00000000-00000000
 */

#define DYNAMIC_MAC_TABLE_ADDR		0x0000FFFF
#define DYNAMIC_MAC_TABLE_FID		0x000F0000
#define DYNAMIC_MAC_TABLE_SRC_PORT	0x00300000
#define DYNAMIC_MAC_TABLE_TIMESTAMP	0x00C00000
#define DYNAMIC_MAC_TABLE_ENTRIES	0xFF000000

#define DYNAMIC_MAC_TABLE_ENTRIES_H	0x03
#define DYNAMIC_MAC_TABLE_MAC_EMPTY	0x04
#define DYNAMIC_MAC_TABLE_RESERVED	0x78
#define DYNAMIC_MAC_TABLE_NOT_READY	0x80

#define DYNAMIC_MAC_FID_S		16
#define DYNAMIC_MAC_SRC_PORT_S		20
#define DYNAMIC_MAC_TIMESTAMP_S		22
#define DYNAMIC_MAC_ENTRIES_S		24
#define DYNAMIC_MAC_ENTRIES_H_S		8

/**
 * MIB_COUNTER_VALUE			00-00000000-3FFFFFFF
 * MIB_COUNTER_VALID			00-00000000-40000000
 * MIB_COUNTER_OVERFLOW			00-00000000-80000000
 */

#define MIB_COUNTER_OVERFLOW		BIT(31)
#define MIB_COUNTER_VALID		BIT(30)

#define MIB_COUNTER_VALUE		0x3FFFFFFF

#define KS_MIB_PACKET_DROPPED_TX_0	0x100
#define KS_MIB_PACKET_DROPPED_TX_1	0x101
#define KS_MIB_PACKET_DROPPED_TX	0x102
#define KS_MIB_PACKET_DROPPED_RX_0	0x103
#define KS_MIB_PACKET_DROPPED_RX_1	0x104
#define KS_MIB_PACKET_DROPPED_RX	0x105

#define MIB_PACKET_DROPPED		0x0000FFFF

#endif
