#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y                                   := board-micrel.o ks8695_utils.o
obj-$(CONFIG_PCI)			+= pci.o
obj-$(CONFIG_CPU_FREQ_INTEGRATOR)	+= cpu.o
